# Site settings

# Setup
title:               Davi Monteiro
tagline:             'Hanc marginis exiguitas non caperet'
description:         'Ph.D. student ğŸ“ <br> Software engineer ğŸ’» <br> Cryptocurrency enthusiast â›ï¸'
url:                 https://davimonteiro.com.br # the base hostname & protocol for your site, e.g. http://example.com
baseurl:             '' # the subpath of your site, e.g. /blog

# Pagination Settings
paginate: 5
paginate_path: "/blog/page:num/"

# Google Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-62517739-1
    anonymizeIp: true

# About/contact
author:
  name: Davi Monteiro
  url: https://twitter.com/davimonteirob
  email: davi.monteiro@lero.ie

# Pages
blog: '/blog'
background: '/background'
activities: '/activities'
publications: '/publications'
projects: '/projects'
awards: '/awards'
about: '/about'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-analytics
  - jekyll-seo-tag
